

POST http://localhost:3002/register
Content-Type: application/json

{
  "username": "adam_rich",
  "name": "Adam Richard",
  "password": "rich@2021",
  "gender": "male",
  "location": "Detroit"
}

####

POST http://localhost:3002/login/
Content-Type: application/json

{
  "username": "adam_rich",
  "password": "rich@2021"
}

####

GET http://localhost:3002/states/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjg2OTc3NzQ2fQ.95yx1btXp2JPv7MoejzcCZENC2qxNCnJ_aPyyWtUFCY
#####


GET http://localhost:3002/states/4/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjg2OTc3NzQ2fQ.95yx1btXp2JPv7MoejzcCZENC2qxNCnJ_aPyyWtUFCY
#####

GET http://localhost:3002/states/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjg2OTc3NzQ2fQ.95yx1btXp2JPv7MoejzcCZENC2qxNCnJ_aPyyWtUFCY
#####

GET http://localhost:3002/districts/10/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjg2OTc3NzQ2fQ.95yx1btXp2JPv7MoejzcCZENC2qxNCnJ_aPyyWtUFCY


POST http://localhost:3002/districts/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjg2OTc3NzQ2fQ.95yx1btXp2JPv7MoejzcCZENC2qxNCnJ_aPyyWtUFCY

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###

POST http://localhost:3002/change-password
Content-Type: application/json

{
  "username": "adam_rich",
  "oldPassword": "rich@2021",
  "newPassword": "rich@2022"
}